# Generated by Django 4.2.4 on 2023-08-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_user_location_user_location_unique'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ManyToManyField(through='weather.User_Location', to='weather.location'),
        ),
    ]
