# Generated by Django 4.2.4 on 2023-08-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_location_log_rename_logs_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
